# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Estimating Indoor Model Flight Times"
author: "Roie R. Black"
copyright: "2022"
logo: ../assets/images/lpp.gif
email: roie.black@gmail.com
description: >-
   Python tool for predicting indoor model flight times.

exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

execute:
  execute_notebooks: auto

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    - replacements
    - smartquotes
      # - substitution


latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - ../assets/references.bib

repository:
  url: https://github.com/rblack42/math-magik-flight-time
  path_to_book: book
  branch: master

html:
  use_issues_button: true
  use_repository_button: true
